---
- name: Reboot Linux servers
  hosts: linux
  gather_facts: false
  become: true

  tasks:
    - name: Reboot Linux server
      command: shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    
    - name: Waiting for a min
      pause:
       seconds: 90

    - name: uptime
      command: uptime
      register: uptime_output

    - name: display
      debug:
        var: uptime_output.stdout_lines
