---
- name: Linux Patching Playbook
  hosts: linux_servers
  gather_facts: true
  become: true

  tasks:
    - name: Update package cache
      yum:
        name: '*'
        state: latest
      register: package_update

    - name: Check if updates are available
      debug:
        msg: "Updates available"
      when: package_update.changed

    - name: Perform system update
      yum:
        name: '*'
        state: latest
      register: package_upgrade
      when: package_update.changed

    - name: Reboot if required
      command: shutdown -r now
      async: 0
      poll: 0
      become: false
      when: package_upgrade.changed

    - name: Wait for server to come back online
      wait_for_connection:
        delay: 30
        timeout: 300