---
- name: Linux OS Parameters Check
  hosts: linux
  gather_facts: yes
  become: true

  tasks:
    - name: Gather OS Parameters
      template:
            src: os_report.j2
            dest: /tmp/os_output_{{ ansible_hostname }}.txt
      delegate_to: localhost
  
    - name: 
      local_action: shell cat /tmp/os_output_* > consolidated_os_output.txt

    - name: Send Email with Attachment
      shell: "echo 'Please find the OS artifacts' | mutt -a consolidated_os_output.txt -s 'Ansible Report' -- christal.manu@gmail.com"
